apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "movies.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- if .Values.mongodb.password }}
  mongodb-password:  {{ .Values.mongodb.password | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
