{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
    chart: {{ include "infrastructure.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: ui
      port: 16686
      targetPort: 16686
  selector:
    app: jaeger
    release: {{ .Release.Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  labels:
    app: jaeger
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  number: 16686
{{- end }}
