apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen:
      activeService: catalog
      previewService: catalog-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: catalog-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: catalog
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: load-data
          image: {{ .Values.image }}
          command:
            - yarn
            - load
          env:
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_PASSWORD
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
      containers:
        - name: catalog
          image: {{ .Values.image }}
          env:
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_PASSWORD
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /catalog/healthz
              port: 8080
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /catalog/healthz
              port: 8080
