apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    {{- include "movies.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "movies"
    dev.okteto.com/endpoints: https://jona-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}/piapia
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
