apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen:
      activeService: api
      previewService: api-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      {{- if .Values.load }}
      initContainers:
        - name: load-data
          image: {{ .Values.image }}
          command:
            - /usr/local/bin/api
            - load-data
      {{- end }}
      containers:
        - name: api
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
