apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: rent
  name: rent
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: rent-canary
      stableService: rent
      steps:
      - setWeight: 25
      - pause: {duration: 30}
      - setWeight: 50
      - pause: {duration: 30}
      - setWeight: 75
      - pause: {duration: 30}
  selector:
    matchLabels:
      app: rent
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
      - image: {{ .Values.image }}
        name: rent
        ports:
        - containerPort: 8080
          name: rent
