apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 60}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.image }}
        name: worker
        command:
          - /usr/local/bin/worker

