apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.image }}
        name: worker
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "jaeger:4317"
        - name: OTEL_SERVICE_NAME
          value: "worker"
        command:
          - /usr/local/bin/worker

