on: 
  pull_request: 
    types:
      - closed

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master    

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}

    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        namespace: movies-pr-${{ github.event.number }}
    
    - name: "Destroy the pipeline"
      uses: okteto/destroy-pipeline@master
      with:
        name: movies-pr-${{ github.event.number }}

    - name: "Delete Namespace"
      uses: okteto/delete-namespace@master
      with:
        name: movies-pr-${{ github.event.number }}