on: 
  pull_request: 
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}

    - name: Delete namespace
      uses: okteto/destroy-preview@latest
      with:
        name: pr-${{ github.event.number }}-${{ secrets.OKTETO_USERNAME }}
